[package]
name = "Class-Task-1-Nov-2019"
version = "0.1.0"
authors = ["Anas452 <anasm9877@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
