[package]
name = "task"
version = "0.1.0"
authors = ["Anas452 <anasm9877@gmail.com>"]
edition = "2018"


[lib]
name = "cal"
path = "mylib/src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
